> 本文包含以下内容
> 1. 捕捉错误
> 2. 抛出错误
> 3. 自定义错误



```python
# coding=utf-8
a = 1/0
print("这一行不会运行，因为第一行就报错了")

```

上面的代码如果放到python中运行会报错`ZeroDivisionError: division by zero`因为分母不能为0

大家可以像一个问题，在我们写代码的过程中，总是避免不了出错，只要出现错误我们的程序就不会再继续运行。错误有两种

一种是写代码过程中出现的语法错误

```python
list1 = [1,2,3,4]
for i in list1  #这里会报错，因为没有加冒号，属于语法错误
    print(i)
#SyntaxError: invalid syntax
```

一种是除语法错误之外的错误

```python
a = 1/0  #这里会报错，因为0不能作为分母  

```

我们要讲的错误处理就是为了解决第二种错误，除语法错误之外的错误

错误处理的本质就是让程序不在纠结迷茫

# 错误捕捉

```python
try:
    a = 1/0
except:
    print("a = 1/0这一句有错误时，就会运行这一句")
else:
    print("a = 1/0这一句没有错误时，就会运行这一句")
finally:
    print("无论a = 1/0这一句有没有错误时，这一句都会运行")
```

如果我们希望获取错误信息

```python
try:
    a = 1/0
except Exception as e:  #这里的Exception代表所有的错误类型，就说是只要是报错，错误都都属于Exception
    print(e)
```

# 错误抛出
使用`raise`关键字来抛出错误
```python
raise 错误的名字("对错误的说明")
```

举个例子

```python
# -*- coding:utf-8 -*-
def convert(list_data):
    if isinstance(list_data,list):
        raise TypeError(u"这个函数的作用对象是一个列表")
    else:
        return [i*i for i in list_data]
```

# 自定义错误

```python
# -*- coding:utf-8 -*-

#定义错误
class MyError(Exception):
    #使用类的继承
    pass

try:
    raise MyError("这是一个我自定义的错误类型")
except MyError as e:
    print(e)
```
